// <auto-generated />
using System;
using IntranetCPT.Infra.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntranetCPT.Infra.Dados.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20190926121451_Inicial2")]
    partial class Inicial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntranetCPT.Dominio.Entidades.Tb_Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnName("Conteudo");

                    b.Property<string>("Introducao")
                        .IsRequired()
                        .HasColumnName("Introducao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Tb_Conteudo");
                });

            modelBuilder.Entity("IntranetCPT.Dominio.Entidades.Tb_Manuais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnName("Arquivo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Tb_Manuais");
                });

            modelBuilder.Entity("IntranetCPT.Dominio.Entidades.Tb_Ramais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnName("Setor");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Tb_Ramais");
                });
#pragma warning restore 612, 618
        }
    }
}
